name: Conversational Flows Designer - Build
on: 
  push:
    branches:
      - 'master'
    tags-ignore:
      - "v*"

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Clean previous build #Cleaning dist, www, node_modules, .stencil
      run: |
        Get-ChildItem .\dist -Recurse |
          ForEach-Object {
          rm -Recurse $_.FullName
        }
        Get-ChildItem .\www -Recurse |
          ForEach-Object {
          rm -Recurse $_.FullName
        }
        Get-ChildItem .\node_modules -Recurse |
          ForEach-Object {
          rm -Recurse $_.FullName
        }
        Get-ChildItem .\.stencil -Recurse |
          ForEach-Object {
          rm -Recurse $_.FullName
        }
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm install
    - name: Run Validate Script
      run: npm run validate