name: Conversational Flows Designer - Build and publish
on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Clean previous build #Cleaning dist, www
      run: |
        Get-ChildItem .\dist -Recurse |
          ForEach-Object {
          rm -Recurse $_.FullName
        }
        Get-ChildItem .\www -Recurse |
          ForEach-Object {
          rm -Recurse $_.FullName
        }
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm install
    - name: Run Validate Script
      run: npm run validate
    - name: publish
      run: npm publish
    - name: Build extension
      run: cmd /c curl --% -u "${{ secrets.USER_NAME }}:${{ secrets.TOKEN }}" -H "Accept:application/vnd.github.everest-preview+json" -H "Content-Type:application/json" -X POST -d "{\"event_type\":\"build_application\",\"client_payload\":{\"from\":\"Conversational-Flows-Designer\"}}" ${{ secrets.WEBHOOK_URL }}
