name: Conversational Flows Designer - Build and publish
on: 
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Clean previous build #Cleaning dist, www, node_modules, .stencil
      run: |
        Get-ChildItem .\dist -Recurse |
          ForEach-Object {
          rm -Recurse $_.FullName
        }
        Get-ChildItem .\www -Recurse |
          ForEach-Object {
          rm -Recurse $_.FullName
        }
        Get-ChildItem .\node_modules -Recurse |
          ForEach-Object {
          rm -Recurse $_.FullName
        }
        Get-ChildItem .\.stencil -Recurse |
          ForEach-Object {
          rm -Recurse $_.FullName
        }
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm install
    - name: Run Validate Script
      run: npm run validate
    - name: publish
      run: |
        $CommitNumber = git rev-list --no-merges --count HEAD
        $packageJSONVersion = (Get-Content package.json) -join "`n" | ConvertFrom-Json | Select -ExpandProperty "version"
        $versionParts = $packageJSONVersion.split(".")
        $major = $versionParts[0]
        $minor = $versionParts[1]
        $version = "$major.$minor.$CommitNumber"
        npm version $version --no-git-tag-version
        npm publish
    - name: Build extension
      run: cmd /c curl --request POST --url ${{ secrets.WEBHOOK_URL }} --header 'authorization:token ${{ secrets.TOKEN }}' -H 'content-type:application/json' -H 'Accept:application/vnd.github.v3+json' -d '{\"ref\":\"refs/heads/beta\"}'
