name: Conversational Flows Designer - Build and publish
on: 
  push:
    tags:
      - "v*"

jobs:
  build:
    env:
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: windows-latest

    steps:
    - name: Clean previous build #Cleaning dist, www, node_modules, .stencil
      run: |
        Get-ChildItem .\dist -Recurse |
          ForEach-Object {
          rm -Recurse $_.FullName
        }
        Get-ChildItem .\www -Recurse |
          ForEach-Object {
          rm -Recurse $_.FullName
        }
        Get-ChildItem .\node_modules -Recurse |
          ForEach-Object {
          rm -Recurse $_.FullName
        }
        Get-ChildItem .\.stencil -Recurse |
          ForEach-Object {
          rm -Recurse $_.FullName
        }
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: npm install
    - name: Run Validate Script
      run: npm run validate
    - name: publish
      run: npm publish --registry=https://registry.npmjs.org/:_authToken=${NPM_TOKEN}"
    - name: Build extension
      run: |
        $commitMessage = git log -1 --pretty=%B
        $commitMessage = $Test = "Worflow dispatch from Conversational-Flows-Designer: - " + $commitMessage
        $dispatchData = '{\"ref\":\"refs/heads/beta\", \"inputs\": {\"commitMessage\":\"'+$CommitMessage+'\"}}'
        cmd /c curl --request POST --url ${{ secrets.WEBHOOK_URL }} --header 'authorization:token ${{ secrets.TOKEN }}' -H 'content-type:application/json' -H 'Accept:application/vnd.github.v3+json' -d $dispatchData
